version: "3"

services:
  logsense-forwarder:
    image: collectivesense/logsense-forwarder
    environment:
      - LOGSENSE_TOKEN="your logsense token"
    ports:
      - "127.0.0.1:24224:24224"
    restart: unless-stopped
